import { describe, it } from 'vitest';
import * as fc from 'fast-check';

import {
  generatedNodeArb,
  generatedNodesArrayArb,
} from './tree-node.arb.js';

/**
 * Used for looking at the tree distributions generated by the arbs.
 */
describe('print generated tree node arbitraries', () => {
  it.only('generated nodes', () => {
    const samples = fc.sample(generatedNodeArb, {
      numRuns: 10,
      seed: 12345,
    });

    for (const [index, generated] of samples.entries()) {
      console.log(`\n--- node ${index + 1} ---`);

      console.dir(generated.node, {
        depth: Infinity,
        colors: false,
      });
    }
  });

  it.only('generated root-level node arrays', () => {
    const samples = fc.sample(generatedNodesArrayArb, {
      numRuns: 5,
      seed: 12345,
    });

    for (const [index, generatedNodes] of samples.entries()) {
      console.log(`\n--- root array ${index + 1} ---`);

      console.dir(
        generatedNodes.map(({ node }) => node),
        {
          depth: Infinity,
          colors: false,
        },
      );
    }
  });
});
